import { ASSERTIONMODES, ASSERTIONNAMES, FUNCTIONMAPPER } from "./index.js";

window.__ASSERTIONMODES = ASSERTIONMODES;
window.__ASSERTIONNAMES = ASSERTIONNAMES;
window.__FUNCTIONMAPPER = FUNCTIONMAPPER;
