import {
  ASSERTIONMODES,
  ASSERTIONNAMES,
  NONDOCKASSERTIONNAMES,
} from "./index.js";

window.__ASSERTIONMODES = ASSERTIONMODES;
window.__ASSERTIONNAMES = ASSERTIONNAMES;
window.__NONDOCKASSERTIONNAMES = NONDOCKASSERTIONNAMES;
