import {
  ASSERTIONMODES,
  ASSERTIONNAMES,
  NONDOCKASSERTIONNAMES,
  FUNCTIONMAPPER,
} from "./index.js";

window.__ASSERTIONMODES = ASSERTIONMODES;
window.__ASSERTIONNAMES = ASSERTIONNAMES;
window.__NONDOCKASSERTIONNAMES = NONDOCKASSERTIONNAMES;
window.__FUNCTIONMAPPER = FUNCTIONMAPPER;
